services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_ENCODING: UTF8
      POSTGRES_USER: medic
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medical
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medic -d medical"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    environment:
      POSTGRES_ENCODING: UTF8
      POSTGRES_HOST: postgres
      POSTGRES_USER: medic
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medical
      POSTGRES_PORT: 5432
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy

  etl:
    build: .
    environment:
      POSTGRES_ENCODING: UTF8
      POSTGRES_HOST: postgres
      POSTGRES_USER: medic
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medical
      POSTGRES_PORT: 5432
      DOCKER_MODE: 'true'
    volumes:
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "python -m etl.loader_pipeline"

volumes:
  postgres_data:
